# Configuration for MkDocs documentation
site_name: ANFIS Toolbox
site_description: A comprehensive Python implementation of Adaptive Neuro-Fuzzy Inference Systems (ANFIS)
site_url: https://dcruzf.github.io/anfis-toolbox/
repo_url: https://github.com/dcruzf/anfis-toolbox
repo_name: dcruzf/anfis-toolbox

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/icon.svg
  favicon: assets/icon.svg

nav:
  - Home: index.md
  - Models:
    - regressor: models/anfis.md
    - classifier: models/anfis-classifier.md
    - fuzzy c-means: models/fuzzy_c-means.md
  - Membership Functions:
    - Gaussian: membership_functions/gaussian.ipynb
    - Two-Sided Gaussian: membership_functions/gaussian-combination.ipynb
    - Generalized Bell: membership_functions/bell.ipynb
    - Pi-shaped: membership_functions/pi.ipynb
    - Triangular: membership_functions/triangular.ipynb
    - Trapezoidal: membership_functions/trapezoidal.ipynb
    - Sigmoidal: membership_functions/sigmoidal.ipynb
    - Difference of Sigmoidal: membership_functions/sigmoidal-difference.ipynb
    - Product of Sigmoidal: membership_functions/sigmoidal-product.ipynb
    - Z-Shaped: membership_functions/zshaped.ipynb
    - Linear Z-Shaped: membership_functions/zshaped-linear.ipynb
    - S-Shaped: membership_functions/sshaped.ipynb
    - Linear S-Shaped: membership_functions/sshaped-linear.ipynb
  - Examples:
    - Basic: examples/basic_example.ipynb
    - Intermediate: examples/intermediate_example.ipynb
    - Advanced: examples/advanced_example.ipynb
  - API Reference:
    - index: api/index.md
    - Membership Functions: api/membership-functions.md
    - Builders: api/builders.md
    - Models: api/models.md
    - Layers: api/layers.md
    - Clustering: api/clustering.md
    - Optimization: api/optim.md
    - Metrics: api/metrics.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            show_source: false
            separate_signature: true
            show_bases: true
            show_root_heading: true
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: false
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      no_input: false
      remove_tag_config:
              remove_input_tags:
                  - hide


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dcruzf
      repo: anfis-toolbox
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dcruzf/anfis-toolbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/anfis-toolbox/


extra_css:
  - css/stylesheets/extra.css

extra_javascript:
  - js/render_latex.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - docs/hooks/test_hook.py

copyright: Copyright &copy; 2025 Daniel França
