# Configuration for MkDocs documentation
site_name: ANFIS Toolbox
site_description: A comprehensive Python implementation of Adaptive Neuro-Fuzzy Inference Systems (ANFIS)
site_url: https://dcruzf.github.io/anfis-toolbox/
repo_url: https://github.com/dcruzf/anfis-toolbox
repo_name: dcruzf/anfis-toolbox

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/logo.png
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Your First Model: getting-started/first-model.md
  - User Guide:
    - Introduction: guide/introduction.md
    - Membership Functions: guide/membership-functions.md
    - Model Architecture: guide/architecture.md
    - Training Methods: guide/training.md
    - Validation & Metrics: guide/validation.md
    - Visualization: guide/visualization.md
    - Configuration: guide/configuration.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Function Approximation: examples/function-approximation.md
    - Multi-Input Systems: examples/multi-input.md
    - Control Systems: examples/control.md
    - Time Series: examples/time-series.md
  - API Reference:
    - Overview: api/overview.md
    - Model: api/model.md
    - Membership Functions: api/membership.md
    - Builders: api/builders.md
    - Validation: api/validation.md
    - Visualization: api/visualization.md
  - Theory:
    - ANFIS Background: theory/background.md
    - Mathematical Foundation: theory/mathematics.md
    - Learning Algorithms: theory/learning.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Release Notes: development/changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            show_source: false
            separate_signature: true
            show_bases: true
            show_root_heading: true
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: false
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dcruzf
      repo: anfis-toolbox
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dcruzf/anfis-toolbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/anfis-toolbox/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 Daniel França
